create table if not exists public.products (
  id bigint generated by default as identity primary key,
  type text not null default 'Jogo' check (type in ('Jogo', 'Console', 'Acessório', 'Colecionável', 'Gift Card', 'Outro')),
  title text not null,
  platform text not null default '',
  brand text not null default '',
  publisher text not null default '',
  genre text not null default '',
  media_format text not null default '',
  region text not null default '',
  condition text not null default 'Usado',
  condition_detail text not null default '',
  condition_notes text not null default '',
  includes text not null default '',
  description text not null default '',
  price_cents integer not null default 0,
  compare_at_price_cents integer,
  stock integer not null default 1,
  store_stock jsonb not null default '{}'::jsonb,
  sku text not null default '',
  age_rating text not null default '',
  players text not null default '',
  online_support text not null default '',
  warranty_notes text not null default '',
  weight_kg numeric(10, 3) not null default 0.2,
  width_cm numeric(10, 2) not null default 14,
  length_cm numeric(10, 2) not null default 17,
  height_cm numeric(10, 2) not null default 2,
  photo_url text not null default '',
  media jsonb not null default '[]'::jsonb,
  status text not null default 'available' check (status in ('available', 'reserved', 'sold', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_created_at_idx on public.products (status, created_at desc);
create index if not exists products_platform_idx on public.products (platform);
create index if not exists products_type_idx on public.products (type);
create index if not exists products_genre_idx on public.products (genre);
create index if not exists products_sku_idx on public.products (sku);
create index if not exists products_condition_idx on public.products (condition);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select on public.products to anon, authenticated;
grant select, insert, update, delete on public.products to service_role;
grant usage, select on sequence public.products_id_seq to service_role;

drop policy if exists "Public can read available products" on public.products;
create policy "Public can read available products"
on public.products
for select
to anon, authenticated
using (status = 'available');

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read product media" on storage.objects;
create policy "Public can read product media"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'product-media');
